### ISSUE TITLE
fails with: cpu lacks required instruction sets

### ISSUE THREAD

**Issue by bmhatfield** [Blitznote/docker-ubuntu-debootstrap#17] opened 2018-06-04 17:34 UTC
I suspect this is related to the requirements for specific kernel versions and SSE4, but attempting to run this on Kubernetes launched using a vanilla GKE cluster fails:

```
kubectl run -i --tty container-test --image=blitznote/debootstrap-amd64:16.04 --restart=Never -- bash
FATAL: cpu lacks required instruction sets
```

<img width="450" alt="screen shot 2018-06-04 at 1 33 12 pm" src="https://user-images.githubusercontent.com/1119967/40932312-ecc8f8d6-67fb-11e8-80b7-28ea622a0361.png">

While I'm not sure there's much to do here, I thought this more-common use case for an image like this would be surprising and interesting.

Thank you!

**Comment by bmhatfield** [comment] 2018-06-04 18:12
I was concerned that there were some limitations of `cos`, Google's Container-Optimized OS, but this fails in the same way with a node powered with `ubuntu` instead.

**Comment by mark-kubacki** [comment] 2018-06-04 18:15
Agreed, I suspect this is a duplicate of #1.

You will need an Intel *Ivy Bridge* (e.g. i5-3xxx, E5-xxxx v2), or *Silvermont* (C2xxx) or later to run this, or AMD's or an other vendor's equivalent. Available instruction sets are checked early, by *libc*, which will fail with this exact error message right away.

I would consider this a bug if your cpu had *SSE 4.1*, *PCLMULQDQ*, and *RDRAND* and so on. In this case please reopen this issue and include the output of `lscpu`. If you use an emulation layer, then please check whether you're not constraining the virtual cpu first. – Thanks!

This independent of *Kubernetes* or any Linux distribution, or any Linux kernel version: The cpu is queried.

**Closed as completed by mark-kubacki** 2018-06-04 18:15 UTC

**Comment by mark-kubacki** [comment] 2018-06-04 18:22
The ratio behind this *eager checks* is this: I've had reports in the past which indicated the operators didn't read the requirements and have been surprised by suddenly stopped processes. Whenever I've been invited to debug this on the target machines, the cause turned out to be cpus without instruction sets used here.  
(You would see `trap: illegal instruction` or similar in the logs.)

I understand any disappointment, but I feel it's better to notify users about peril early so they can consider a different image or utilize services of a hosting provider who offers tech no older than seven years old.

**Comment by bmhatfield** [comment] 2018-06-04 18:34
Thank you for your response!

Looking at `lscpu`, I can see that I am missing the `rdrand` instruction set.

```
bhatfield@gke-cluster-1-default-pool-0a24b57b-fvxt:~$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU @ 2.60GHz
Stepping:              7
CPU MHz:               2600.000
BogoMIPS:              5200.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt aes xsave avx hypervisor lahf_lm pti retpoline tsc_adjust xsaveopt
```

**Comment by mark-kubacki** [comment] 2018-06-04 18:57
It's not only *rdrand*. Anyway, sorry.

**Comment by bmhatfield** [comment] 2018-06-04 19:38
For anyone searching this error and stumbling across this issue - this _is_ solvable on Google Compute / GCE /GKE!

When you create your Kubernetes cluster or other GCE instances, you can specify the [minimum CPU platform](https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform#specifications) to something with these instruction sets (as mentioned in #1 - something "newer than 7y ago"), or simply [pick a region where new CPUs are the default](https://cloud.google.com/compute/docs/regions-zones/#available). Thanks @wmark for adding these checks up-front to this container and saving everyone a lot of confusion and frustration later!
