### ISSUE TITLE
FATAL: kernel too old

### ISSUE THREAD

**Issue by chinkung** [Blitznote/docker-ubuntu-debootstrap#19] opened 2019-01-03 07:44 UTC
I try to install some package in Dockerfile

```
FROM blitznote/debase:18.04

RUN apt update && \
    apt install -y git gcc g++ make
```

However, there is an error during build

```
.
.
.
Setting up git (1:2.20.1-2bn) ...
Setting up gcc (4:8.2.0-1ubuntu1) ...
Setting up g++ (4:8.2.0-1ubuntu1) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Processing triggers for libc-bin (2.28-17bn) ...
FATAL: kernel too old
Aborted (core dumped)
FATAL: kernel too old
Aborted (core dumped)
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 134
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Could you please check ?

**Comment by mark-kubacki** [comment] 2019-01-03 15:32
Works as intended.

See [README](https://github.com/Blitznote/debase/blob/a7a250f2ede46e89319be2187444b93c7922f573/README.md), see [minkernel](https://github.com/Blitznote/debase/blob/a7a250f2ede46e89319be2187444b93c7922f573/Dockerfile#L10).

If it were not for that, I would close it for formal reasons.

**Closed as completed by mark-kubacki** 2019-01-03 15:32 UTC
Labels: invalid
