### ISSUE TITLE
`CURL_OPENSSL_3 xxx` not found in libcurl

### ISSUE THREAD

**Issue by lbogdan** [Blitznote/docker-ubuntu-debootstrap#13] opened 2018-02-05 00:12 UTC
Hello,

I have a `libcurl` issue which seems to be related to #10, still a bit different. It is in `php-curl` from [Ondřej's PHP PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php), and the error that I get is:
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'curl.so'
(tried: /usr/lib/php/20170718/curl.so (/usr/lib/php/20170718/curl.so: symbol curl_multi_add_handle, version CURL_OPENSSL_3 not defined in file libcurl.so.4 with link time reference), 
/usr/lib/php/20170718/curl.so.so (/usr/lib/php/20170718/curl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

A quick way to reproduce it:
```bash
$ docker run --rm -it blitznote/debootstrap-amd64:16.04 bash
$ apt-get update \
&& apt-get -y install dirmngr \
&& apt-key adv --keyserver keyserver.ubuntu.com --recv-key 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C \
&& echo 'deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main' >/etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list \
&& apt-get -y update && apt-get -y install php-cli php-curl \
&& php -v
```
which for me gives this output. [link to pastebin removed; Mark]

**Comment by lbogdan** [comment] 2018-02-05 00:27
Btw, I'm using this image:
```
$ docker images | grep blitz
REPOSITORY                           TAG             IMAGE ID          CREATED           SIZE
blitznote/debootstrap-amd64          16.04           27281ca571c0      6 days ago        38.6MB
```

**Comment by mark-kubacki** [comment] 2018-02-05 01:24
Please do not link to external resources.

I gather the cause of your issue is that a `libcurl.so.4` does not export symbol  
`CURL_OPENSSL_3  curl_multi_add_handle`.

For some years now *curl* has arrived at [CURL_**_4](https://github.com/curl/curl/blame/a19afaccfeb5a77c15fdfc1c2be16fb27828cefc/lib/libcurl.vers.in#L9) (please note the trailing 4).

Following commands give you a list of version and symbol tables (you would need to correct that path):
```bash
readelf -V $(realpath -P libcurl-boringssl.so) | sed -n '/.gnu.version_d/,/^$/p'
objdump -T $(realpath -P libcurl-boringssl.so)
```

… which shows me that the function has been exported as `CURL_OPENSSL_4 curl_multi_add_handle`, and as `CURL_OPENSSL_3 curl_multi_add_handle`. An alias I added into the binary as workaround.

Are you sure you're not using two *libcurl.so.••*?

**Comment by lbogdan** [comment] 2018-02-05 07:27
Sorry, the output was too large to paste here.

As I showed above, I start from a `blitznote/debootstrap-amd64:16.04` image and install `php-cli` and `php-curl` (and `dirmngr`, but that's only needed by `apt-key`, in my Dockerfile I purge it and autoclean after I add the key):

```
46de2f3ea4dc / $ dpkg -l 'libcurl*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libcurl3:amd64 7.99.9-1alia amd64        Alias for libcurl3-boringssl.
ii  libcurl3-borin 7.58.0-44    amd64        easy-to-use client-side URL trans

46de2f3ea4dc / $ ls -al /usr/lib/x86_64-linux-gnu/libcurl*
lrwxrwxrwx 1 root root 47 Jan 25 18:46 /usr/lib/x86_64-linux-gnu/libcurl-boringssl.so.3 -> ../x86_64-cros-linux-gnu/libcurl-boringssl.so.3
lrwxrwxrwx 1 root root 47 Jan 25 18:46 /usr/lib/x86_64-linux-gnu/libcurl-boringssl.so.4 -> ../x86_64-cros-linux-gnu/libcurl-boringssl.so.4
lrwxrwxrwx 1 root root 51 Jan 25 18:46 /usr/lib/x86_64-linux-gnu/libcurl-boringssl.so.4.5.0 -> ../x86_64-cros-linux-gnu/libcurl-boringssl.so.4.5.0
lrwxrwxrwx 1 root root 22 Mar  6  2016 /usr/lib/x86_64-linux-gnu/libcurl.so.3 -> libcurl-boringssl.so.3
lrwxrwxrwx 1 root root 22 Mar  6  2016 /usr/lib/x86_64-linux-gnu/libcurl.so.4 -> libcurl-boringssl.so.4

46de2f3ea4dc / $ ls -al /usr/lib/x86_64-cros-linux-gnu/libcurl*
lrwxrwxrwx 1 root root      26 Jan 25 18:46 /usr/lib/x86_64-cros-linux-gnu/libcurl-boringssl.so.3 -> libcurl-boringssl.so.4.5.0
lrwxrwxrwx 1 root root      26 Jan 25 18:46 /usr/lib/x86_64-cros-linux-gnu/libcurl-boringssl.so.4 -> libcurl-boringssl.so.4.5.0
-rwxr-xr-x 1 root root 1465480 Jan 25 18:46 /usr/lib/x86_64-cros-linux-gnu/libcurl-boringssl.so.4.5.0
```
Indeed, I can see "your" libcurl exports `CURL_OPENSSL_4 curl_multi_add_handle`:
```
46de2f3ea4dc / $ objdump -T /usr/lib/x86_64-linux-gnu/libcurl.so.4 | grep multi_add_handle
00000000000ec450 g    DF .text  00000000000001cc  CURL_OPENSSL_4 curl_multi_add_handle
```
but the "regular" Ubuntu libcurl exports `CURL_OPENSSL_3 curl_multi_add_handle` - this is still from a blitznote image, following your advice [here](https://github.com/Blitznote/debase/issues/10#issuecomment-340186398):
```
ae22cccfcb79 app $ dpkg -l 'libcurl*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libcurl3:amd64 7.47.0-1ubun amd64        easy-to-use client-side URL trans
ii  libcurl3-borin 7.58.0-44    amd64        easy-to-use client-side URL trans

ae22cccfcb79 app $ objdump -T /usr/lib/x86_64-linux-gnu/libcurl.so.4 | grep multi_add_handle
0000000000035590 g    DF .text  0000000000000172  CURL_OPENSSL_3 curl_multi_add_handle
```

Let me know if I can help with more debugging.

**Comment by mark-kubacki** [comment] 2018-02-05 17:17
No, I've a pretty good idea what's going on here. After addressing some issues which arose with the new `glibc 2.28` I will publish a new issue with a changed libcurl very soon.

You've not checked all output. For example, my `readelf -V …` call from above shows that `CURL_OPENSSL_3` indeed exports those symbols, after a `CURL_OPENSSL_4` and its alias `CURL_BORINGSSL_4`. (Duplicate tables to maintain compatibility, and an alias because there's not substantial differences between {OPENSSL,BORINGSSL} exports.)

In any case, you would've searched for duplicate libraries like this:
```bash
find / -name 'libcurl*' -type f
```
… or, provided nothing removed the *trigger* from package `libc6` which maintains the cache (though a binary can opt to load from other locations, which for example PHP indeed does; but to be complete):
```
ldconfig -p
```

**Comment by lbogdan** [comment] 2018-02-05 18:03
Nope, no duplicate libcurl:
```
867201cd47da / $ find / -name 'libcurl*' -type f
/usr/lib/x86_64-cros-linux-gnu/libcurl-boringssl.so.4.5.0
/usr/share/lintian/overrides/libcurl3
/usr/share/lintian/overrides/libcurl3-boringssl
/var/lib/dpkg/info/libcurl3-boringssl:amd64.shlibs
/var/lib/dpkg/info/libcurl3:amd64.list
/var/lib/dpkg/info/libcurl3-boringssl:amd64.list
/var/lib/dpkg/info/libcurl3-boringssl:amd64.triggers
```
```
867201cd47da / $ ldconfig -p | grep 'found\|libcurl'
90 libs found in cache `/etc/ld.so.cache'
        libcurl-boringssl.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcurl-boringssl.so.4
```
```
867201cd47da / $ ldd /usr/lib/php/20170718/curl.so
        linux-vdso.so.1 =>  (0x00007fffc1992000)
        libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f16acc09000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f16ac9ed000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f16ac670000)
        /lib64/ld-linux-x86-64.so.2 (0x0000564eb0c2e000)
```

**Comment by mark-kubacki** [comment] 2018-02-05 18:30
Yes, symbols get mixed up. As mentioned before, I've added another workaround and will push it asap with the new images.

**Comment by lbogdan** [comment] 2018-02-05 21:10
Nice, I'll keep an eye on the new images, thanks!

And thanks for all the effort put in this project! I base all my docker images on blitznote/debootstrap-amd64. :smile:

**Comment by mark-kubacki** [comment] 2018-02-05 21:31
You're welcome!

And thanks for notifying me of the issue. I have to rely on the community for the cases I don't catch with my testing.

Reopening because an update will actually close this.

**Comment by mark-kubacki** [comment] 2018-02-06 16:24
Some notes:

* You don't need **dirmgr**. That's what `get-gpg-key` is for.
* Use `blitznote/debase:16.04`, which is an alias for `debootstrap-amd64:16.04` on amd64, to be ready for multi-arch images. For example, I might publish an image for *≤Ivy Bridge*, and definitely one for *aarch64*.
* `docker run … bash` – the `bash` suffix is not needed. I've already set *bash* as default shell and entrypoint.

**Comment by lbogdan** [comment] 2018-02-06 17:04
Thanks for the pointers!

Although that particular key doesn't seem to be found by `get-gpg-key`
```
867201cd47da / $ get-gpg-key E5267A6C
curl: (22) The requested URL returned error: 404 Not found
curl: (22) The requested URL returned error: 404
```
vs.
```
867201cd47da / $ curl 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE5267A6C'
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
[...]
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.1.6
Comment: Hostname: keyserver.ubuntu.com

mI0ESX35nAEEALKDCUDVXvmW9n+T/+3G1DnTpoWh9/1xNaz/RrUH6fQKhHr568F8hfnZP/2C
[...]
```

Also, from what I understand by reading the script, it prints the key to stdout, but I need to add it to apt's keyring.

**Comment by mark-kubacki** [comment] 2018-02-06 17:12
You need to use the full keyid.

----
I've to set this issue to *wontfix* because the symbol is indeed exported under version `CURL_OPENSSL_3` as well as `_4` as per [the docs](https://www.akkadia.org/drepper/dsohowto.pdf) (page 38):

```
HIDDEN
{
  local:
    __*;
    _rest*;
    _save*;
};

CURL_OPENSSL_4
{
  global:
// …
    curl_multi_add_handle;
// …
    curl_*;
  local: *;
};

CURL_OPENSSL_3
{
  global:
// …
    curl_multi_add_handle;
// …
// no wildcard exports
} CURL_OPENSSL_4;

```

A different order is not possible or any new packages would rely on `CURL_OPENSSL_3`, which is the wrong way to do this.

I suggest that `/usr/lib/php/20170718/curl.so` stops relying on that obsolete version, or links against a `libcurl.so.3` and not `libcurl.so.4` (please note the trailing numbers).

----
Workarounds:

1. FYI, I publish packages for PHP, too. You could use those. They're updated every Monday at least.
2. Install Ubuntu's libcurl. `apt-get -t xenial --allow-downgrades install libcurl3`

**Closed as completed by mark-kubacki** 2018-02-06 17:12 UTC

**Comment by lbogdan** [comment] 2018-02-06 17:37
> You need to use the fill keyid.

Did you mean full? If so, it still can't find it:
```
867201cd47da / $ get-gpg-key 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
curl: (22) The requested URL returned error: 404
curl: (22) The requested URL returned error: 404 Not found
```

----

> I suggest that /usr/lib/php/20170718/curl.so stops relying on that obsolete version, or links against a libcurl.so.3 and not libcurl.so.4 (please note the trailing numbers).

Yeah, I was thinking about reporting this to Ondřej, too, but as long as they compile for "vanilla" Ubuntu I don't think it's an issue for them.

> FYI, I publish packages for PHP, too.

Where can I find them?

**Comment by mark-kubacki** [comment] 2018-02-06 18:20
I will get back to this in about 2hrs. By shuffling around some package names, and makeing libcurl3-alias optional, I think we can get everything installed without conflicts.

* In any case, *glibc* symbol resolution seems to be broken if versions are used. I've even dissected this with an hex editor, and the symbol is definitely exported properly.
* Debian/Ubuntu have some years ago lazyly, to maintain compatibility, downgraded curl's _4 to _3 and left it like that. Instead of recompiling all packages (which they do for new releases anyway) they've stuck with this anachronism.
* Packages are linked with the wrong library (although using `-lcurl` is per-se not wrong, `-lcurl.so.3` or similar should've been used; the symlink is there).

But, at this point it's shifting blame. We'll solve this.

----
https://hub.blitznote.com/src/ci-php ← click on CI/CD; due to changes in Docker the latest builds are broken, but the packages are generated properly, in earlier stages.

**Comment by lbogdan** [comment] 2018-02-06 19:40
Figured it out, it needed a `0x` prefix on the key (I saw the usage in `ci-php`'s `compile.sh` :smile:).

Took a look at `ci-php`, although it looks interesting, I think I'll stick with Ondřej's packages for the moment.

**Comment by mark-kubacki** [comment] 2018-02-06 20:12
Okay, this is what I'll do:

* rename my package to `libcurl4`  
Given that the package family is installed by default and the dev-package is called `libcurl-boringssl…`, nothing should break here.
* remove libcurl3 (the alias), but retain all the links as orphaned so they get removed if Ubuntu's package is installed

If anyone installs libcurl3 he/she will silently lose the new crypto, TLSv1.3, and http2 support, but at least the package should be usable right away.

**Comment by mark-kubacki** [comment] 2018-02-06 21:08
In about an hour the new images will be up. This should work (I did test it with the most recent images; could work with previous ones as well):

```bash
apt-get -q update \
 && source /etc/os-release \
 && apt-get -y --no-install-recommends --allow-downgrades install \
      libcurl3/${UBUNTU_CODENAME}

get-gpg-key 0x14AA40EC0831756756D7F66C4F4EA0AAE5267A6C \
 | gpg2 --no-default-keyring --keyring /etc/apt/trusted.gpg --import

printf "deb [arch=amd64] http://ppa.launchpad.net/ondrej/php/ubuntu xenial main\n" \
>/etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list \
 && apt-get -q update \
 && apt-get -y install php-cli php-curl \
 && php -v

rm -f /etc/apt/sources.list.d/ondrej-ubuntu-php-xenial.list
gpg2 --no-default-keyring --keyring /etc/apt/trusted.gpg --batch --delete-keys \
  0x14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
apt-get clean
```

In a nutshell, install Ubuntu's `libcurl3` first, downgrading the existing one (which is just some symlinks anyway), and then install whatever wants the obsolete `CURL_OPENSSL_3`.
